vaadin:
  launch-browser: false

spring:
  application:
    name: application

  profiles:
    active: @activatedProperties@

server:
  port: 8081


encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY}

bank-app:
  url: ${BANK_APP_URL:http://localhost:8080}